feat: update templates

diff --git a/.github_templates/workflows/safecd_pr.yml b/.github_templates/workflows/safecd_pr.yml
--- a/.github_templates/workflows/safecd_pr.yml
+++ b/.github_templates/workflows/safecd_pr.yml
@@ -19,13 +19,19 @@ jobs:
       - uses: actions/checkout@v3
         with:
           submodules: recursive
-      - uses: kilnfi/safecd@1.0.2
+          token: ${{ secrets.PAT }}
+      - uses: kilnfi/safecd@1.0.3-rc.29
         id: safecd
         with:
           rpc: ${{ secrets.RPC }}
       - name: Comment PR
-        if : ${{ steps.safecd.outputs.hasPrComment == 'true' }}
+        if: ${{ steps.safecd.outputs.hasPrComment == 'true' }}
         uses: thollander/actions-comment-pull-request@v2
         with:
           filePath: ./PR_COMMENT
           comment_tag: 'safecd'
+      - name: Check failed proposals
+        if: ${{ steps.safecd.outputs.hasFailedProposals == 'true' }}
+        run: |
+          echo "crashing ci due to failed proposal simulations"
+          exit 1
